// internal/theme/presets.go
package theme

var presets = []Theme{
	{
		Name:        "default",
		DisplayName: "默认 / Default",
		Colors: ColorScheme{
			Background: "#1a1a1a",
			Foreground: "#ffffff",
			Muted:      "#626262",
			Primary:    "#00d7ff",
			Success:    "#00ff00",
			Error:      "#ff0000",
			Warning:    "#ffff00",
			Info:       "#00d7ff",
			Border:     "#4a4a4a",
			Accent:     "#ff6b35",
			Highlight:  "#ffff00",
			PaletteBg:       "#2a2a2a",
			PaletteActive:   "#3a3a3a",
			PaletteInactive: "#1a1a1a",
		},
	},
	{
		Name:        "ocean",
		DisplayName: "海洋 / Ocean",
		Colors: ColorScheme{
			Background: "#0c2340",
			Foreground: "#e0f0ff",
			Muted:      "#5a8ab0",
			Primary:    "#00bfff",
			Success:    "#00ff88",
			Error:      "#ff4d4d",
			Warning:    "#ffd700",
			Info:       "#00bfff",
			Border:     "#1e4d7b",
			Accent:     "#00ced1",
			Highlight:  "#00ffff",
			PaletteBg:       "#1a3a5c",
			PaletteActive:   "#2a4a6c",
			PaletteInactive: "#0c2340",
		},
	},
	{
		Name:        "forest",
		DisplayName: "森林 / Forest",
		Colors: ColorScheme{
			Background: "#1a2819",
			Foreground: "#e8f5e9",
			Muted:      "#6b8e6b",
			Primary:    "#4caf50",
			Success:    "#76ff03",
			Error:      "#ff5252",
			Warning:    "#ffeb3b",
			Info:       "#4caf50",
			Border:     "#2e4d2e",
			Accent:     "#8bc34a",
			Highlight:  "#c6ff00",
			PaletteBg:       "#2a3a29",
			PaletteActive:   "#3a4a39",
			PaletteInactive: "#1a2819",
		},
	},
	{
		Name:        "sunset",
		DisplayName: "日落 / Sunset",
		Colors: ColorScheme{
			Background: "#2d1b2d",
			Foreground: "#fff8e1",
			Muted:      "#a08080",
			Primary:    "#ff6b35",
			Success:    "#ffeb3b",
			Error:      "#ff1744",
			Warning:    "#ff9800",
			Info:       "#ff6b35",
			Border:     "#4a2a4a",
			Accent:     "#ff4081",
			Highlight:  "#ffd740",
			PaletteBg:       "#3d2b3d",
			PaletteActive:   "#4d3b4d",
			PaletteInactive: "#2d1b2d",
		},
	},
	{
		Name:        "light",
		DisplayName: "亮色 / Light",
		Colors: ColorScheme{
			Background: "#ffffff",
			Foreground: "#1a1a1a",
			Muted:      "#757575",
			Primary:    "#0066cc",
			Success:    "#008800",
			Error:      "#cc0000",
			Warning:    "#cc8800",
			Info:       "#0066cc",
			Border:     "#e0e0e0",
			Accent:     "#ff6b35",
			Highlight:  "#0066cc",
			PaletteBg:       "#f5f5f5",
			PaletteActive:   "#e8e8e8",
			PaletteInactive: "#ffffff",
		},
	},
}
